
import { GoogleGenAI, Modality, Chat } from "@google/genai";
import type { GenerateContentResponse } from "@google/genai";
import type { ChatMessage } from '../types';

if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
const imageModel = 'gemini-2.5-flash-image';
const chatModelName = 'gemini-2.5-flash';

function base64ToImagePart(base64: string) {
    // Expected format: "data:image/jpeg;base64,..."
    const parts = base64.split(';base64,');
    if (parts.length !== 2) {
        throw new Error("Invalid base64 string format");
    }
    const mimeType = parts[0].split(':')[1];
    const data = parts[1];
    return {
        inlineData: {
            mimeType,
            data,
        },
    };
}

export async function generateInitialDesign(base64Image: string, style: string): Promise<string> {
    const imagePart = base64ToImagePart(base64Image);
    const textPart = {
        text: `Reimagine this room in a ${style} style. The new image should be a photorealistic rendering of the redesigned space, maintaining the original room's structure.`,
    };

    const response: GenerateContentResponse = await ai.models.generateContent({
        model: imageModel,
        contents: { parts: [imagePart, textPart] },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    const firstPart = response.candidates?.[0]?.content?.parts[0];
    if (firstPart && 'inlineData' in firstPart && firstPart.inlineData) {
        const { mimeType, data } = firstPart.inlineData;
        return `data:${mimeType};base64,${data}`;
    }

    throw new Error("No image was generated by the API.");
}

export async function refineDesign(base64Image: string, prompt: string): Promise<string> {
    const imagePart = base64ToImagePart(base64Image);
    const textPart = {
        text: `Based on this image, apply the following change: "${prompt}". The new image should be a photorealistic rendering of the redesigned space, maintaining the core style.`,
    };

    const response: GenerateContentResponse = await ai.models.generateContent({
        model: imageModel,
        contents: { parts: [imagePart, textPart] },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    const firstPart = response.candidates?.[0]?.content?.parts[0];
    if (firstPart && 'inlineData' in firstPart && firstPart.inlineData) {
        const { mimeType, data } = firstPart.inlineData;
        return `data:${mimeType};base64,${data}`;
    }
    
    throw new Error("No refined image was generated by the API.");
}

export async function getChatResponse(history: ChatMessage[], newUserMessage: string): Promise<Chat> {
    const chat: Chat = ai.chats.create({
      model: chatModelName,
      config: {
          systemInstruction: 'You are an AI interior design assistant. Your responses should be brief, encouraging, and focused on helping the user refine their design. After confirming a change, ask them what they would like to do next.',
      },
    });
    return chat;
}
